# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 755c1fc76bf9a94951128d7fa090202c2c8c1b5af9226f1f306f519ba4dbf259b92f57d9c713edcb832717cfec819116ce640a5e6a9b9a350d2e56dbea147d82

test:
  secret_key_base: 481fe064b1d7f8840bbcec205ec17d2ce612ce24f364b587be3376de1895579c40cc0cf121c833c0596620682bbeb08e0bfa5a68641f56005b62b0f98952840d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
